# Generated by Django 4.0 on 2021-12-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStagesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('phase_id', models.IntegerField()),
                ('sensor_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.projectstage')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDailyupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plumbing_count', models.IntegerField()),
                ('electrial_count', models.IntegerField()),
                ('commissioning_count', models.IntegerField()),
                ('plumber_count', models.IntegerField()),
                ('helper_count', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contractor_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.projectcontractor')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.projectstagesmapping')),
                ('user_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssigningDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.projectcontractor')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.projectstagesmapping')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appApi.user')),
            ],
        ),
    ]
